<template>
    <i class="icon iconfont" :class="[addtype, addInterval]" v-show="type"></i>
</template>

<script>
    export default {
        name: 'icon',
        props: ['type', 'interval'],
        data () {
            return {
                show: true
            }
        },
        computed: {
            addInterval: function () {
                if (this.interval) {
                    return 'interval'
                }
            },
            addtype: function () {
                return {
                    ' bw-fapiaoshengcheng': this.type === 'fapiaoshengcheng',
                    ' bw-pipeixinxi': this.type === 'pipeixinxi',
                    ' bw-qianshouxinxi': this.type === 'qianshouxinxi',
                    ' bw-wuliuxinxi': this.type === 'wuliuxinxi',
                    ' bw-chayan': this.type === 'chayan',
                    ' bw-renzheng': this.type === 'renzheng',
                    ' bw-baocun': this.type === 'baocun',
                    ' bw-fenpeikaipiaoyuan': this.type === 'jiebangkaipiaoyuan',
                    ' bw-chuangjianyonghu': this.type === 'chuangjianyonghu',
                    ' bw-daochukehuxinxi': this.type === 'daochukehuxinxi',
                    ' bw-bianji': this.type === 'bianji',
                    ' bw-daorukehuxinxi': this.type === 'daorukehuxinxi',
                    ' bw-tijiaokaipiaoshenqingdan': this.type === 'tijiaokaipiaoshenqingdan',
                    ' bw-chaifen': this.type === 'chaifen',
                    ' bw-duqushuikongpan': this.type === 'duqushuikongpan',
                    ' bw-shengchengdaikai': this.type === 'shengchengdaikai',
                    ' bw-hebing': this.type === 'hebing',
                    ' bw-daochuexcelwenjian': this.type === 'daochuexcelwenjian',
                    ' bw-fanhuishangyiye': this.type === 'fanhuishangyiye',
                    ' bw-tianjiakehu': this.type === 'tianjiakehu',
                    ' bw-daochuduanxinjilu': this.type === 'daochuduanxinjilu',
                    ' bw-daochumingxi': this.type === 'daochumingxi',
                    ' bw-daochuzhuxinxi': this.type === 'daochuzhuxinxi',
                    ' bw-daochuwordwendang': this.type === 'daochuwordwendang',
                    ' bw-dayin': this.type === 'dayin',
                    ' bw-zuofei': this.type === 'zuofei',
                    ' bw-renzhengxinxi': this.type === 'renzhengxinxi',
                    ' bw-jiankongxinxifanxie': this.type === 'jiankongxinxifanxie',
                    ' bw-wangshangbaoshui': this.type === 'wangshangbaoshui',
                    ' bw-chakanjiankongxinxi': this.type === 'chakanjiankongxinxi',
                    ' bw-dangqianpiaohao': this.type === 'dangqianpiaohao',
                    ' bw-qingqiuliushuihao': this.type === 'qingqiuliushuihao',
                    ' bw-fapiaotaitou': this.type === 'fapiaotaitou',
                    ' bw-saoma': this.type === 'saoma',
                    ' bw-huoqudangqianhaoma': this.type === 'huoqudangqianhaoma',
                    ' bw-yebianjushezhi': this.type === 'yebianjushezhi',
                    ' bw-kaiju': this.type === 'kaiju',
                    ' bw-linggou': this.type === 'linggou',
                    ' bw-zancun': this.type === 'zancun',
                    ' bw-fenfa': this.type === 'fenfa',
                    ' bw-queding': this.type === 'queding',
                    ' bw-xiayibu': this.type === 'xiayibu',
                    ' bw-tiaoguo': this.type === 'tiaoguo',
                    ' bw-shangyibu': this.type === 'shangyibu',
                    ' bw-xiazai': this.type === 'xiazai',
                    ' bw-jianceshuikongxinxi': this.type === 'jianceshuikongxinxi',
                    ' bw-chakanxiangqing': this.type === 'chakanxiangqing',
                    ' bw-fengxianguanli': this.type === 'fengxianguanli',
                    ' bw-lijijinru': this.type === 'lijijinru',
                    ' bw-shuikongshebeiguanli': this.type === 'shuikongshebeiguanli',
                    ' bw-quanxianguanli': this.type === 'quanxianguanli',
                    ' bw-kehuguanli': this.type === 'kehuguanli',
                    ' bw-qianzhanggongdan': this.type === 'qianzhanggongdan',
                    ' bw-shangpinguanli': this.type === 'shangpinguanli',
                    ' bw-zhucemagongju': this.type === 'zhucemagongju',
                    ' bw-chaxun': this.type === 'chaxun',
                    ' bw-qiyeguanli': this.type === 'qiyeguanli',
                    ' bw-fapiaoguanli': this.type === 'fapiaoguanli',
                    ' bw-yichangfapiaorenzheng': this.type === 'abnormalInvoice',
                    ' bw-weirenzhengfapiaoyujing': this.type === 'unidentifiedInvoice',
                    ' bw-kaipiaoshenqing': this.type === 'kaipiaoshenqing',
                    ' bw-liushuidanguanli': this.type === 'liushuidanguanli',
                    ' bw-renzhengjieguochaxun': this.type === 'identifyResult',
                    ' bw-gouxuanrenzheng': this.type === 'checkedIdentify',
                    ' bw-saomarenzheng': this.type === 'scanCodeIdentify',
                    ' bw-daikaifapiaoguanli': this.type === 'daikaifapiaoguanli',
                    ' bw-fapiaochaxun': this.type === 'invoiceinquiry',
                    ' bw-hongzixinxibiaoguanli': this.type === 'quxihongzixinxibiaoguanliao',
                    ' bw-heguichayan': this.type === 'complianceCheck',
                    ' bw-shujuchuli': this.type === 'shujuchuli',
                    ' bw-fapiaochayan': this.type === 'invoiceCheck',
                    ' bw-chaxuntongji': this.type === 'chaxuntongji',
                    ' bw-chaobaoshuiguanli': this.type === 'chaobaoshuiguanli',
                    ' bw-shouye': this.type === 'shouye',
                    ' bw-fapiaoliuzhuan': this.type === 'fapiaoliuzhuan',
                    ' bw-xiaoxiang': this.type === 'xiaoxiang',
                    ' bw-jinxiang': this.type === 'jinxiang',
                    ' bw-fapiaokaiju': this.type === 'fapiaokaiju',
                    ' bw-xitongguanli': this.type === 'xitongguanli',
                    ' bw-jichuxinxiguanli': this.type === 'jichuxinxiguanli',
                    ' bw-gongdanguanli': this.type === 'gongdanguanli',
                    ' bw-yundanju': this.type === 'yundanju',
                    ' bw-yunguiji': this.type === 'yunguiji',
                    ' bw-yunkaipiao': this.type === 'yunkaipiao',
                    ' bw-shuikongshangpinbianmatongbu': this.type === 'shuikongshangpinbianmatongbu',
                    ' bw-tongbu': this.type === 'tongbu',
                    ' bw-yidongduan_tabbargongzuotai': this.type === 'cloudConsole',
                    ' bw-qiyeheimingdan': this.type === 'enterpriseBlackList',
                    ' bw-shangpinheimingdan': this.type === 'goodsBlackList',
                    ' bw-tianjia': this.type === 'tianjia',
                    ' bw-shanchu': this.type === 'shanchu',
                    ' bw-yunkongzhitai': this.type === 'yunkongzhitai',
                    ' bw-piliangshanchu': this.type === 'piliangshanchu',
                    ' bw-pilianghuanyuan': this.type === 'pilianghuanyuan',
                    ' bw-daoruexcelxinxi': this.type === 'daoruexcelxinxi',
                    ' bw-daorubianma': this.type === 'daorubianma',
                    ' bw-chushihua': this.type === 'chushihua',
                    ' bw-piliangdaoru': this.type === 'piliangdaoru',
                    ' bw-piliangdaochu': this.type === 'piliangdaochu',
                    ' bw-shangla': this.type === 'shangla',
                    ' bw-xiala': this.type === 'xiala',
                    ' bw-chakanjibenxinxi': this.type === 'chakanjibenxinxi',
                    ' bw-tongbu1': this.type === 'tongbu1',
                    ' bw-jinxiangshuiemingxibiao': this.type === 'jinxiangshuiemingxibiao',
                    ' bw-biaogeguanli': this.type === 'biaogeguanli',
                    ' bw-jinxiangshuiebaobiao': this.type === 'jinxiangshuiebaobiao',
                    ' bw-canshushezhi': this.type === 'canshushezhi',
                    ' bw-bangding': this.type === 'bangding',
                    ' bw-daochu': this.type === 'daochu',
                    ' bw-jijiangyuqifapiao': this.type === 'jijiangyuqifapiao',
                    ' bw-daoru': this.type === 'daoru',
                    ' bw-feifangweishuikongfapiao': this.type === 'feifangweishuikongfapiao',
                    ' bw-jiechubangding': this.type === 'jiechubangding',
                    ' bw-renzhengqisuoding': this.type === 'renzhengqisuoding',
                    ' bw-zhuanru': this.type === 'zhuanru',
                    ' bw-zhuanchu': this.type === 'zhuanchu',
                    ' bw-luru': this.type === 'luru',
                    ' bw-gongdanguanli1': this.type === 'gongdanguanli1',
                    ' bw-shangsanjiao': this.type === 'shangsanjiao',
                    ' bw-xiasanjiao': this.type === 'xiasanjiao',
                    'bw-yidongduan_navclose': this.type === 'yidongduan_navclose',
                    'bw-xitongguanli1': this.type === 'xitongguanli1',
                    'bw-xiaoxiang1': this.type === 'xiaoxiang1',
                    'bw-yidongduan_conbanbenshengji': this.type === 'yidongduan_conbanbenshengji',
                    'bw-yidongduan_condelete': this.type === 'yidongduan_condelete'
                }
            }
        }
    }
</script>

<style lang="scss">
    .interval {
        padding-right: 10px;
    }
</style>
